class OrchestratorAPI:

    async def run(self, query): ...

    async def chat(self, history, message): ...

    async def answer_with_tools(self, prompt): ...

    async def get_context(self, query): ...

    async def update_memory(self, event): ...

    async def write_kg_triple(self, head, relation, tail, metadata={}): ...

    async def query_kg(self, graph_query): ...

    async def plan_task(self, query): ...

    async def execute_plan(self, plan): ...

    async def validate(self, output, constraints): ...

    async def finalize(self, response, context): ...
